# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d75325b46c7477acf393b338af981d4d4984fe29e3604b713dfb1ac868b2d2ddecab9456c80f134d06ad69c13f491fef31ce69694997efd8dadaf86747a00f49

test:
  secret_key_base: 3e53392872f2d3f84896f1b7693fde2c1e08dd256a93baf0254e4d26f00d73206a52cf05af080d7cb6c6a925c12c8782dde016528ddc543a5a3d9c69e1bfd4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
